sudo: false
language: node_js
node_js:
  - "8"
notifications:
  disabled: true
install:
  - npm install -g codecov
  - npm install
script:
  - dotenv -e .env.test sequelize db:create
  - dotenv -e .env.test sequelize db:migrate
  - npm test
  - codecov
services:
  - redis-server
  - postgresql
