sudo: false
language: node_js
node_js:
  - "8"
notifications:
  disabled: true
install:
  - npm install -g codecov
  - npm install
script:
  - sequelize db:create --env test
  - NODE_ENV=test sequelize db:migrate --env test
  - npm test
  - codecov
services:
  - redis-server
  - postgresql
